import random

number = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]

random_number = int(random.choice(number))

user_input = int(input("Guess the number from 1 to 10: "))
print("Number generated by the computer is:", random_number)
print("You have guessed: ", user_input)

if (user_input == random_number):
        print(f"You have guessed right.\n {user_input} is the right choice.")
else:
    print("Try Again.\nYou have entered wrong number.")
